### ISSUE TITLE
This example may not be valid

### ISSUE THREAD

**Issue by warriorpostman** [snipcart/snipcart-gatsby-integration#1]
I just had an email exchange with the folks at Snipcart regarding this example and the plugin currently listed on GatsbyJS' plugin page. He responded as such:

"...
The plugin is not actually maintained. We write lots of content about how to integrate Snipcart with some tools, however, we don't build integrations that we maintain.
..."

MIght be worth noting in the README that this is no longer considered blessed by the vendor?

**Comment by JeanSebTr** [comment]
Hi @warriorpostman 

This repo is on the Snipcart org, the same team on the support is maintaining those repos ;)

Our demos are meant as live implementations of the steps presented in our blog posts. It should work as long as not much have changed in Gatsby.

If there are some specifics things that are broken since recent updates, could you point those to us? This will allow us to evaluate if it's worth updating the repo and the blog post and also give proper indications in the notice as to what is to look out for.


Thanks!

**Comment by warriorpostman** [comment]
So sorry for the late reply. I think the problem was maybe that I"m using Gatsby V2, or that I tried using the Snipcart plugin (https://www.gatsbyjs.org/packages/gatsby-plugin-snipcart/). When I used the validation function in the Snipcart dashboard, it basically said I didn't have Snipcart configured, so I wasn't sure if that was because I configured the plugin wrong. I saw a few different avenues (examples) provided for Snipcart and wasn't sure which was considered the "blessed" approach for using Snipcart with Gatsby. Appreciate the response though!
